name: tfm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiofiles=23.1.0
  - aioftp=0.21.4
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - anyio=3.5.0
  - aom=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=9.0.0
  - asciitree=0.3.3
  - asdf=2.15.1
  - asdf-astropy=0.4.0
  - asdf-coordinates-schemas=0.2.0
  - asdf-standard=1.0.3
  - asdf-transform-schemas=0.3.0
  - asdf-unit-schemas=0.1.0
  - astropy=5.3.2
  - astropy-healpix=0.7
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.1.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - blinker=1.6.2
  - blosc=1.21.4
  - bokeh=3.2.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.0
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - cairo=1.16.0
  - cdflib=1.1.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.1.0
  - cryptography=39.0.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask=2023.8.0
  - dask-core=2023.8.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.8.0
  - drms=0.6.4
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.5.0
  - fasteners=0.17.3
  - fftw=3.3.10
  - flatbuffers=2.0.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gast=0.4.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - glog=0.6.0
  - glymur=0.12.8
  - google-auth=2.22.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - greenlet=2.0.2
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.34
  - h5netcdf=1.2.0
  - h5py=3.9.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.1
  - importlib-metadata=6.8.0
  - importlib-resources=6.0.1
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.7
  - isodate=0.6.1
  - jack=1.9.22
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.3.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=3.0.8
  - jxrlib=1.1
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgoogle-cloud=2.3.0
  - libgpg-error=1.47
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=252
  - libthrift=0.16.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - matplotlib-scalebar=0.8.1
  - mistune=0.8.4
  - mpg123=1.31.3
  - mpl_animators=1.1.0
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nb_conda_kernels=2.3.1
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nccl=2.18.3.1
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numcodecs=0.11.0
  - numpy=1.25.2
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=1.1.1v
  - opt_einsum=3.3.0
  - orc=1.8.0
  - packaging=23.1
  - palettable=3.3.3
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parfive=2.0.2
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - protobuf=4.21.12
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - pyarrow=9.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyerfa=2.0.0.3
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.6
  - re2=2022.06.01
  - readline=8.2
  - reproject=0.11.0
  - requests=2.31.0
  - requests-file=1.5.1
  - requests-oauthlib=1.3.1
  - requests-toolbelt=1.0.0
  - rsa=4.9
  - s2n=1.0.10
  - scikit-image=0.21.0
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - seaborn-image=0.7.0
  - semantic_version=2.10.0
  - send2trash=1.8.0
  - setuptools=68.1.2
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sqlalchemy=2.0.20
  - sqlite=3.42.0
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - sunpy=5.0.0
  - tblib=1.7.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - tensorflow-gpu=2.10.0
  - termcolor=2.3.0
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tifffile=2023.8.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.66.1
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.3.7
  - wheel=0.41.1
  - widgetsnbextension=4.0.8
  - wrapt=1.15.0
  - xarray=2023.7.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2023.7.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zarr=2.16.0
  - zeep=4.2.1
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.16.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
